services:
  # Nginx Reverse Proxy (for Railway deployment)
  nginx:
    image: nginx:alpine
    container_name: ventiapi-nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend-build:/usr/share/nginx/html
    networks:
      - scanner-network
    depends_on:
      - frontend
      - web-api

  # Frontend React App (build only)
  frontend:
    build: ./frontend
    container_name: ventiapi-frontend
    volumes:
      - frontend-build:/shared
    networks:
      - scanner-network

  # Web API Backend
  web-api:
    build: ./scanner-service/web-api
    container_name: ventiapi-web-api
    ports:
      - "8000:8000"
    volumes:
      - shared-results:/shared/results
      - shared-specs:/shared/specs
      - /var/run/docker.sock:/var/run/docker.sock  # Access to Docker daemon
    networks:
      - scanner-network
    env_file:
      - .env.local
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  # Redis for job queue and caching (optional but recommended)
  redis:
    image: redis:7-alpine
    container_name: ventiapi-redis
    ports:
      - "6379:6379"
    networks:
      - scanner-network
    volumes:
      - redis-data:/data

  # PostgreSQL Database (for Cedar RAG system)
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ventiapi-postgres
    ports:
      - "54320:5432"
    networks:
      - scanner-network
    environment:
      - POSTGRES_USER=rag_user
      - POSTGRES_PASSWORD=rag_pass
      - POSTGRES_DB=rag_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/dumps:/dumps
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag_user -d rag_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Scanner service (builds the image for web-api to use)
  scanner:
    build:
      context: .
      dockerfile: scanner.Dockerfile
    image: ventiapi-scanner
    container_name: ventiapi-scanner-builder
    volumes:
      - shared-results:/shared/results
      - shared-specs:/shared/specs
    networks:
      - scanner-network
    environment:
      - PYTHONUNBUFFERED=1
    command: ["echo", "Scanner image built"]
    profiles: ["build-only"]  # Only runs when explicitly requested

  # Scanner Worker (for job queue mode - optional for local dev)
  scanner-worker:
    build:
      context: .
      dockerfile: scanner-worker.Dockerfile
    volumes:
      - shared-results:/shared/results
      - shared-specs:/shared/specs
    networks:
      - scanner-network
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    profiles: ["jobqueue"]  # Only runs in job queue mode
    scale: 2  # Run 2 workers by default

  # ZAP Scanner (builds the image for web-api to use)
  zap:
    build:
      context: .
      dockerfile: zap.Dockerfile
    image: ventiapi-zap
    container_name: ventiapi-zap-builder
    volumes:
      - shared-results:/zap/wrk:rw
      - shared-specs:/zap/specs:ro
    networks:
      - scanner-network
    command: ["echo", "ZAP scanner image built"]
    profiles: ["build-only"]  # Only runs when explicitly requested

  # Cedar Frontend (Next.js with Cedar OS)
  cedar-frontend:
    build:
      context: ./cedar-frontend
      dockerfile: Dockerfile.nextjs
      args:
        - NEXT_PUBLIC_MASTRA_URL=http://localhost:4111
        - NEXT_PUBLIC_SCANNER_SERVICE_URL=http://localhost:8000
        - NEXT_PUBLIC_SCANNER_USERNAME=${ADMIN_USERNAME:-MICS295}
        - NEXT_PUBLIC_SCANNER_PASSWORD=${ADMIN_PASSWORD:-MaryMcHale}
    container_name: cedar-frontend
    ports:
      - "3001:3000"  # Different port to avoid conflict with existing frontend
    networks:
      - scanner-network
    env_file:
      - .env.local
    environment:
      - NEXT_PUBLIC_MASTRA_URL=http://localhost:4111
      - MASTRA_API_URL=http://cedar-mastra:4111
      - SCANNER_SERVICE_URL=http://web-api:8000
      - NEXT_PUBLIC_SCANNER_SERVICE_URL=http://localhost:3000
      - NEXT_PUBLIC_SCANNER_USERNAME=${ADMIN_USERNAME:-MICS295}
      - NEXT_PUBLIC_SCANNER_PASSWORD=${ADMIN_PASSWORD:-MaryMcHale}
      - NODE_ENV=production
    depends_on:
      - cedar-mastra
      - web-api

  # Cedar Mastra Backend (AI Agent Server)
  cedar-mastra:
    #platform: linux/amd64  # Use x86_64 for LibSQL native module support
    build:
      context: ./cedar-frontend
      dockerfile: Dockerfile.mastra
    container_name: cedar-mastra
    ports:
      - "4111:4111"
    networks:
      - scanner-network
    env_file:
      - ./cedar-frontend/.env
      - .env.local
    environment:
      - SCANNER_SERVICE_URL=http://web-api:8000
      - SCANNER_USERNAME=${ADMIN_USERNAME:-MICS295}
      - SCANNER_PASSWORD=${ADMIN_PASSWORD:-MaryMcHale}
      - DATABASE_URL=postgresql://rag_user:rag_pass@postgres:5432/rag_db
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy
      web-api:
        condition: service_started

volumes:
  shared-results:
  shared-specs:
  redis-data:
  postgres-data:
  frontend-build:

networks:
  scanner-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: scanner-br0