components:
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
info:
  description: OpenAPI v3 specs for VAmPI
  title: VAmPI
  version: '0.1'
openapi: 3.0.1
paths:
  /users/v1/_debug:
    get:
      description: Displays all details for all users
      operationId: api_views.users.debug
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  users:
                    items:
                      properties:
                        admin:
                          example: false
                          type: boolean
                        email:
                          example: mail1@mail.com
                          type: string
                        password:
                          example: pass1
                          type: string
                        username:
                          example: name1
                          type: string
                      type: object
                    type: array
                type: object
          description: See all details of the users
      summary: Retrieves all details for all users
      tags:
      - users
  /users/v1/login:
    post:
      description: Login to VAmPI
      operationId: api_views.users.login_user
      requestBody:
        content:
          application/json:
            schema:
              type: object
        description: Username of the user
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  auth_token:
                    example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NzAxNjA2MTcsImlhdCI6MTY3MDE2MDU1Nywic3ViIjoiSm9obi5Eb2UifQ.n17N4AxTbL4_z65-NR46meoytauPDjImUxrLiUMSTQw
                    type: string
                  message:
                    example: Successfully logged in.
                    type: string
                  status:
                    enum:
                    - success
                    - fail
                    example: success
                    type: string
                type: object
          description: Sucessfully logged in user
        '400':
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: Password is not correct for the given username.
                    type: string
                  status:
                    enum:
                    - fail
                    example: fail
                    type: string
                type: object
          description: Invalid request
      summary: Login to VAmPI
      tags:
      - users
servers:
- url: ''
