apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
  namespace: ventiapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - name: web-api
        image: ventiapi-web-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: JWT_SECRET
          value: "your-jwt-secret-here"
        - name: DEFAULT_ADMIN_USERNAME
          value: "MICS295"
        - name: DEFAULT_ADMIN_PASSWORD
          value: "MaryMcHale"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
  namespace: ventiapi
spec:
  selector:
    app: web-api
  ports:
  - port: 8000
    targetPort: 8000