apiVersion: v1
kind: Namespace
metadata:
  name: ventiapi
  labels:
    name: ventiapi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scanner-service-account
  namespace: ventiapi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scanner-job-manager
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scanner-job-manager-binding
subjects:
- kind: ServiceAccount
  name: scanner-service-account
  namespace: ventiapi
roleRef:
  kind: ClusterRole
  name: scanner-job-manager
  apiGroup: rbac.authorization.k8s.io